#' Compute the multidimensional ESS for the sample
#' @param x Sample generated by LIPS (matrix)
#' @param A Configuration matrix
#'
#' @export
computeMESS <- function(x, A){
  ## ESS as in paper Vats, Flegal, Jones
  # Need to project the coordinates as they are fundamentally dependent
  A <- as.matrix(A)
  c <- ncol(A)

  x <- as.matrix(x)
  nChains <- max(x[ncol(x)-2,])
  nSample <- nrow(x)/nChains
  nVar <- ncol(x)-3

  # Columns of Q after rank(A) span ker(A)
  tol = 1e-05
  qr_A <- qr(t(A), tol = tol)
  Q <- qr.Q(qr_A, complete = TRUE)
  rank_A <- qr_A$rank

  if (rank_A == c) {
    stop("A has trivial null space.")
  }

  B = Q[, seq(rank_A + 1L, c)]

  X = list(nChains)
  for(i in 1:nChains){
    X[[i]] <- x[((i-1)*nChains+(1:nSample)),1:nVar]
  }

  # Translation does not affect covariance or ESS
  Z = list(nChains)
  for(i in 1:nChains){
    Z[[i]] <- sweep(X[[i]], 2, X[[i]][1, ], FUN = "-") %*% B
  }

  mcmcse::multiESS(
    do.call(rbind, Z),
    covmat = rbmCov(Z)
  )
}
