#' Replace negative rows with NA
#' @param x Sample generated by LIPS (matrix)
#'
#' @export
onlyPositive <- function(x){
  t(apply(X = x,
          MARGIN = 1,
          FUN = function(row) if(any(row[1:(length(row)-3)] <= -1)){c(rep(NA, length(row) - 3), row[(length(row)-2):length(row)])} else {row}))
}
